// Auto-generated by scripts/generate-portkey-models.ts - DO NOT edit manually

export type ApiType =
	| "anthropic-messages"
	| "openai-responses"
	| "openai-completions";

export interface PortkeyModel {
	id: string;
	name: string;
	api: ApiType;
	reasoning: boolean;
	input: ("text" | "image")[];
	cost: {
		input: number;
		output: number;
		cacheRead: number;
		cacheWrite: number;
	};
	contextWindow: number;
	maxTokens: number;
}

export const PORTKEY_MODELS: Record<ApiType, Record<string, PortkeyModel>> = {
	"anthropic-messages": {
		"@vertex-ai/anthropic.claude-haiku-4-5@20251001": {
			id: "@vertex-ai/anthropic.claude-haiku-4-5@20251001",
			name: "Claude Haiku 4 5",
			api: "anthropic-messages",
			reasoning: false,
			input: ["text", "image"],
			cost: {
				input: 1,
				output: 5,
				cacheRead: 0.1,
				cacheWrite: 1.25,
			},
			contextWindow: 200000,
			maxTokens: 64000,
		},
		"@vertex-ai/anthropic.claude-opus-4-5@20251101": {
			id: "@vertex-ai/anthropic.claude-opus-4-5@20251101",
			name: "Claude Opus 4 5",
			api: "anthropic-messages",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 5,
				output: 25,
				cacheRead: 0.5,
				cacheWrite: 6.25,
			},
			contextWindow: 200000,
			maxTokens: 32000,
		},
		"@vertex-ai/anthropic.claude-opus-4-6": {
			id: "@vertex-ai/anthropic.claude-opus-4-6",
			name: "Claude Opus 4 6",
			api: "anthropic-messages",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 5,
				output: 25,
				cacheRead: 0.5,
				cacheWrite: 6.25,
			},
			contextWindow: 200000,
			maxTokens: 32000,
		},
		"@vertex-ai/anthropic.claude-sonnet-4-5@20250929": {
			id: "@vertex-ai/anthropic.claude-sonnet-4-5@20250929",
			name: "Claude Sonnet 4 5",
			api: "anthropic-messages",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 3,
				output: 15,
				cacheRead: 0.3,
				cacheWrite: 3.75,
			},
			contextWindow: 200000,
			maxTokens: 64000,
		},
	},
	"openai-responses": {
		"@azure-openai-foundry/gpt-5.1-chat": {
			id: "@azure-openai-foundry/gpt-5.1-chat",
			name: "GPT 5.1 Chat",
			api: "openai-responses",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 0,
				output: 0,
				cacheRead: 0,
				cacheWrite: 0,
			},
			contextWindow: 128000,
			maxTokens: 16384,
		},
		"@azure-openai-foundry/gpt-5.1-codex": {
			id: "@azure-openai-foundry/gpt-5.1-codex",
			name: "GPT 5.1 Codex",
			api: "openai-responses",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 1.25,
				output: 10,
				cacheRead: 0.125,
				cacheWrite: 0,
			},
			contextWindow: 128000,
			maxTokens: 16384,
		},
		"@azure-openai-foundry/gpt-5.1-codex-mini": {
			id: "@azure-openai-foundry/gpt-5.1-codex-mini",
			name: "GPT 5.1 Codex Mini",
			api: "openai-responses",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 0.25,
				output: 2,
				cacheRead: 0.025,
				cacheWrite: 0,
			},
			contextWindow: 128000,
			maxTokens: 16384,
		},
		"@azure-openai-foundry/gpt-5.2": {
			id: "@azure-openai-foundry/gpt-5.2",
			name: "GPT 5.2",
			api: "openai-responses",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 1.75,
				output: 14,
				cacheRead: 0.175,
				cacheWrite: 0,
			},
			contextWindow: 128000,
			maxTokens: 16384,
		},
		"@azure-openai-foundry/gpt-5.2-chat": {
			id: "@azure-openai-foundry/gpt-5.2-chat",
			name: "GPT 5.2 Chat",
			api: "openai-responses",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 0,
				output: 0,
				cacheRead: 0,
				cacheWrite: 0,
			},
			contextWindow: 128000,
			maxTokens: 16384,
		},
		"@azure-openai-foundry/gpt-5.2-codex": {
			id: "@azure-openai-foundry/gpt-5.2-codex",
			name: "GPT 5.2 Codex",
			api: "openai-responses",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 1.75,
				output: 14,
				cacheRead: 0.175,
				cacheWrite: 0,
			},
			contextWindow: 128000,
			maxTokens: 16384,
		},
	},
	"openai-completions": {},
};
